-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS henkilo CASCADE;
DROP TABLE IF EXISTS travelDestination CASCADE;
DROP TABLE IF EXISTS COUNTRY CASCADE;
DROP TABLE ID EXISTS JOINTABLE; 
